batch_size: 128
clear_exp_checkpoints: true
collision_penalty: true
collision_penalty_factor: 2000
dist_threshold: 0.04
epoch: 800
hf_project_path: kijjjj/test-model1
lr: 1.0e-04
metrics_log_epoch_frequency: 2
mr_threshold: 0.02
optimizer: adamw
push_to_hf: false
step_weights_factor: 7
train_data_dir: csv/train_pre
val_data_dir: csv/val_pre
weight_decay: 0.0001
start_prediction_time: 0.2
is_transformer: true
