data_augment:
- ALONG_AXIS_LIST:
  - x
  NAME: random_world_flip
- NAME: random_world_rotation
  WORLD_ROT_ANGLE:
  - -0.78539816
  - 0.78539816
- NAME: random_world_scaling
  WORLD_SCALE_RANGE:
  - 0.95
  - 1.05
fusion:
  args: []
  core_method: IntermediateFusionDatasetV2
loss:
  args:
    stage1:
      cls:
        alpha: 0.25
        gamma: 2.0
        type: SigmoidFocalLoss
        weight: 2.0
      dir:
        type: WeightedSoftmaxClassificationLoss
        weight: 0.2
      encode_rad_error_by_sin: true
      iou: &id001
        codewise: true
        sigma: 3.0
        type: WeightedSmoothL1Loss
        weight: 1.0
      pos_cls_weight: 2.0
      reg:
        codewise: true
        sigma: 3.0
        type: WeightedSmoothL1Loss
        weight: 2.0
    stage2:
      cls:
        type: WeightedSigmoidBinaryCELoss
        weight: 1.0
      iou: *id001
      reg:
        code_weights:
        - 20.0
        reduction: mean
        sigma: 3.0
        type: WeightedSmoothL1Loss
        weight: 1.0
  core_method: fpvrcnn_loss
lr_scheduler:
  core_method: multistep
  gamma: 0.1
  step_size:
  - 10
  - 20
model:
  args:
    D: 52
    H: 832
    N: 4
    T: 5
    W: 2816
    activate_stage2: true
    anchor_num: 2
    head:
      num_cls: 2
      num_dir: 4
      num_input: 128
      num_iou: 2
      num_pred: 14
      use_dir: true
    lidar_range: &id002
    - -140.8
    - -41.6
    - -10.6
    - 140.8
    - 41.6
    - 10.6
    map2bev:
      feature_num: 128
    matcher: none
    mean_vfe:
      num_point_features: 4
    post_processer: &id003
      gt_range: *id002
      anchor_args:
        D: 52
        H: 832
        W: 2816
        cav_lidar_range: *id002
        feature_stride: 8
        h: 1.56
        l: 3.9
        num: 2
        r:
        - 0
        - 90
        vd: 0.4
        vh: 0.1
        vw: 0.1
        w: 1.6
      core_method: FpvrcnnPostprocessor
      max_num: 100
      nms_thresh: 0.15
      order: hwl
      target_args:
        neg_threshold: 0.45
        pos_threshold: 0.6
        score_threshold: 0.5
    roi_head:
      dp_ratio: 0.3
      in_channels: 32
      n_fc_neurons: 256
      num_cls: 1
      roi_grid_pool:
        grid_size: 6
        mlps:
        - - 64
          - 64
        - - 64
          - 64
        n_sample:
        - 16
        - 16
        pool_method: max_pool
        pool_radius:
        - 0.8
        - 1.6
    spconv:
      num_features_in: 4
      num_features_out: 64
    ssfa:
      feature_num: 128
    voxel_size: &id004
    - 0.1
    - 0.1
    - 0.4
    vsa:
      enlarge_selection_boxes: true
      features_source:
      - bev
      - x_conv1
      - x_conv2
      - x_conv3
      - x_conv4
      - raw_points
      num_keypoints: 4096
      num_out_features: 32
      point_source: raw_points
      sa_layer:
        raw_points:
          mlps:
          - - 16
            - 16
          - - 16
            - 16
          n_sample:
          - 16
          - 16
          pool_radius:
          - 0.4
          - 0.8
        x_conv1:
          downsample_factor: 1
          mlps:
          - - 16
            - 16
          - - 16
            - 16
          n_sample:
          - 16
          - 16
          pool_radius:
          - 0.4
          - 0.8
        x_conv2:
          downsample_factor: 2
          mlps:
          - - 32
            - 32
          - - 32
            - 32
          n_sample:
          - 16
          - 32
          pool_radius:
          - 0.8
          - 1.2
        x_conv3:
          downsample_factor: 4
          mlps:
          - - 64
            - 64
          - - 64
            - 64
          n_sample:
          - 16
          - 32
          pool_radius:
          - 1.2
          - 2.4
        x_conv4:
          downsample_factor: 8
          mlps:
          - - 64
            - 64
          - - 64
            - 64
          n_sample:
          - 16
          - 32
          pool_radius:
          - 2.4
          - 4.8
  core_method: fpvrcnn
name: fpvrcnn_intermediate_fusion
optimizer:
  args:
    eps: 1.0e-10
    weight_decay: 0.0001
  core_method: Adam
  lr: 0.002
postprocess: *id003
preprocess:
  args:
    max_points_per_voxel: 5
    max_voxel_test: 70000
    max_voxel_train: 36000
    voxel_size: *id004
  cav_lidar_range: *id002
  core_method: SpVoxelPreprocessor
  keep_original_lidar: true
root_dir: opv2v_data_dumping/train
train_params:
  batch_size: 2
  epoches: 40
  eval_freq: 1
  max_cav: 10
  save_freq: 1
validate_dir: simulation_output/data_dumping/sample
yaml_parser: load_voxel_params
