name: Lint, Format, Type and Unused code Check

on: [ pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run ruff check
        uses: astral-sh/ruff-action@v3
        with:
          args: "check"

  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run ruff format check with diff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: pip install mypy
      - name: Run mypy
        run: mypy .
        continue-on-error: true

  unused-code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: pip install deadcode
      - name: Run deadcode
        run: deadcode .

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: >-
            check-case-conflict
            check-docstring-first
            check-executables-have-shebangs
            check-illegal-windows-names
            check-json
            check-merge-conflict --assume-in-merge
            check-shebang-scripts-are-executable
            check-symlinks
            check-toml
            check-vcs-permalinks
            check-xml
            check-yaml --exclude opencda/coperception_models/.*
            destroyed-symlinks
            end-of-file-fixer
            name-tests-test
            pretty-format-json --autofix
            requirements-txt-fixer
            trailing-whitespace
            --all-files
