name: Lint, Format, Type and Unused code Check

on: [ pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run ruff check
        uses: astral-sh/ruff-action@v3
        with:
          args: "check"

  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run ruff format check with diff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: pip install mypy mypy-protobuf grpcio-tools
      - name: Generate protobufs modules
        run: |
          python -m grpc_tools.protoc \
            -I opencda/core/common/communication/messages \
            --python_out=opencda/core/common/communication/protos/cavise \
            --mypy_out=opencda/core/common/communication/protos/cavise \
            opencda/core/common/communication/messages/capi.proto
      - name: Run mypy
        run: mypy .
        continue-on-error: true

  unused-code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: pip install deadcode
      - name: Run deadcode
        run: deadcode .

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: ruff-check,ruff-format,pretty-format-json
        with:
          extra_args: >-
            --all-files
